### ISSUE TITLE
1.14.3

### ISSUE THREAD

**Issue by ghost** [codetaylor/ct-watercan#13]
Like to have this mod in 1.14.3 for my private server soon. Any plans for that, or should I do it myself in my fork and make a pull request?

**Comment by codetaylor** [comment]
Thank you for the offer, however, I will not accept a pull request to update this to 1.14.

When I port my mods forward, I will start with the smaller mods first, mods like this one. Through the process of updating my smaller mods, I will gain insight into the process. The insight will be valuable to me later when I port my larger mods.
