### ISSUE TITLE
[1.14] No crafting recipes

### ISSUE THREAD

**Issue by SlimJefe** [codetaylor/ct-watercan#15]
Using mod version 2.0.1 and forge version 28.1.90
No recipes show in JEI and trying the recipes from the CurseForge images does not work either.
[Using this modpack if it matters](https://www.curseforge.com/minecraft/modpacks/team-rustic-1-14)

**Comment by Partonetrain** [comment]
Need recipe JSONS for 1.14. /resources/data/watercan/recipes/

For example: 

```
{
  "type": "crafting_shaped",
  "pattern": [
    "mb ",
    "mwm",
    " m "
  ],
  "key": {
    "m": {
      "item": "minecraft:stone"
    },
    "b": {
      "item": "minecraft:bone_meal"
    },
	"w": {
      "item": "minecraft:wooden_bowl"
    }
	
  },
  "result": {
    "item": "watercan:watercan.stone"
  }
}
```
