### ISSUE TITLE
Curseforge config link broken on changing master branch to 1.14 instead of 1.12

### ISSUE THREAD

**Issue by Bluberry-Kat** [codetaylor/ct-watercan#17]
would be fixed by changing `https://github.com/codetaylor/watercan/blob/master/CONFIG.md` to `https://github.com/codetaylor/watercan/blob/master/1.12/CONFIG.md` or adding CONFIG.md to the 1.14 branch (assuming it's still applicable, which it might not be)

**Comment by codetaylor** [comment]
Thanks!
