### ISSUE TITLE
[Request] Consume water source block when filling watering can

### ISSUE THREAD

**Issue by SeriousCreeper** [codetaylor/ct-watercan#3]
Heya! 

First of all, really loving this mod, it's nice and simple and the textures are beautiful <3 

I'm currently working on a modpack that uses finite water, and was wondering if we could get a config option to consume a water source block when you refill the watering cans? 

I think it could be ignored how full/empty the can is, even filling a tiny bit should probably consume it (kinda encourages you to empty it first too). Or not allow refilling until it's completely empty.

Would that be something that could be added?

Cheers,
SC

**Comment by codetaylor** [comment]
Yeah, that sounds great!

I've been wanting to iterate on this for a while and now I have an excuse.

**Comment by codetaylor** [comment]
Added in https://github.com/codetaylor/ct-watercan/commit/e5a4047f4022722b9de2ef9da066f21a3548a10f

Available in version 1.12.2-0.5.5

**Comment by SeriousCreeper** [comment]
Thank you so much! :D
